from os import getenv

import redis
from dotenv import load_dotenv
from selenium import webdriver
from telethon import TelegramClient

load_dotenv("Soheil/.env")

# EA_URLS
EA_LOGIN_PATH = getenv("EA_LOGIN_PATH")

# CRAWLER CONFIGS
DRIVER = webdriver.Chrome()

# ELEMENTS XPATHs
START_LOGIN_BUTTON = getenv("START_LOGIN_BUTTON")
EMAIL_INPUT = getenv("EMAIL_INPUT")
PASSWORD_INPUT = getenv("PASSWORD_INPUT")
SEND_CODE = getenv("SEND_CODE")
LOGIN_BUTTON = getenv("LOGIN_BUTTON")
TWO_FACTOR_CODE_INPUT = getenv("TWO_FACTOR_CODE_INPUT")
TWO_FACTOR_SIGN_IN_BUTTON = getenv("TWO_FACTOR_SIGN_IN_BUTTON")
SIGNED_IN_BY_CONSOLE_TEXT = getenv("SIGNED_IN_BY_CONSOLE_TEXT")
SIDNED_IN_BY_CONSOL_BUTTON = getenv("SIDNED_IN_BY_CONSOL_BUTTON")
TWO_STEP_CODE_INVALID = getenv("TWO_STEP_CODE_INVALID")
PASSWORD_OR_EMAIL_IS_INCORRECT = getenv("PASSWORD_OR_EMAIL_IS_INCORRECT")
MESSAGE_FROM_EA_XPATH = getenv("MESSAGE_FROM_EA_XPATH")

# REDIS
REDIS_ORDER_CHANNEL = getenv("REDIS_ORDER_CHANNEL")
REDIS_ADMIN_CHANNEL = getenv("REDIS_ADMIN_CHANNEL")
REDIS_HOST = getenv("REDIS_HOST")
REDIS_PORT = getenv("REDIS_PORT")
REDIS_PASSWORD = getenv("REDIS_PASSWOR")

# TELETON CONFIG
BOT_TOKEN = getenv("BOT_TOKEN")
API_ID = getenv("API_ID")
API_HASH = getenv("API_HASH")
TELE_CLIENT = TelegramClient(
    BOT_TOKEN,
    API_ID,
    API_HASH,
)

# REDIS SETTINGS
CLIENT = redis.StrictRedis(
    host=REDIS_HOST,
    port=REDIS_PORT,
    decode_responses=True,
)

### MONGO
MONGO_URI = getenv("MONGO_URI")
